// <auto-generated />
namespace GunShop.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DbV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202012161629287_DbV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
